#!/usr/bin/php
<?php

namespace common;

use common\fabrics\WorkspacesFabric;
use common\helpers\DoublyLinkedList;

spl_autoload_register(function($class){
    require dirname(__DIR__) . '/' . str_replace('\\', '/', $class) . '.php';
});

$isBack = isset(getopt('', ['back'])['back']) ? true : false;

$ws = WorkspacesFabric::create();
$ar = $ws->current()->windows()->list();
$currentWindowId = $ws->current()->windows()->current()->id;

$tabOrder = __DIR__ . '/runtime/tabOrder_' . ($ws->current()->num) ?? 'noNum';

if($file = file_get_contents($tabOrder)){
    $ll = unserialize($file);
}else{
    $ll = new DoublyLinkedList([]);
}

$oldIds = $ll->getItems();

foreach($ar as $window){
    $ids[$window->id] = $window->id;
}

foreach ($oldIds as $id)
{
    if(isset($ids[$id])){
        $newIds[] = $id;
        unset($ids[$id]);
    }
}

foreach ($ids as $id){
    $newIds[] = $id;
}

$ll = new DoublyLinkedList($newIds);
$ll->rewindToValue($currentWindowId);

print_r($ll);

if($isBack){
    $ll->prev();
}else{
    $ll->next();
}

shell_exec("i3-msg '[con_id=" . $ll->current() . "] focus'");


file_put_contents($tabOrder, serialize($ll));
